# docker-compose.yaml
version: '3.8'

services:
  # 1. PostgreSQL Database (For LangGraph Memory)
  postgres_db:
    image: postgres:15-alpine
    container_name: ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  # 2. Redis (For Semantic Caching)
  redis_cache:
    image: redis:7-alpine
    container_name: ai_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. Your FastAPI Application
  web_app:
    build: .
    container_name: ai_fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./sandbox:/code/sandbox
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_db:5432/postgres
      - REDIS_URL=redis://redis_cache:6379
      # CHANGED: Added HOST_SANDBOX_DIR so the Docker SDK maps the correct host path
      - HOST_SANDBOX_DIR=${PWD}/sandbox
    env_file:
      - .env
    depends_on:
      - postgres_db
      - redis_cache

volumes:
  postgres_data:
  redis_data: